import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

const businesses = [
  {
    name: "Licorería El Castillo",
    slug: "licoreria-el-castillo",
    category: "LICORERIA",
    subcategory: "Vinoteca",
    zone: "Centro",
    address: "Av. Bolívar, Centro de Los Teques",
    phone: "0212-3214567",
    whatsapp: "584121234567",
    instagram: "@licoreriaelcastillo",
    hours: "Lun-Sáb 8:00-20:00, Dom 9:00-14:00",
    priceRange: "$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Vinos nacionales e importados, ron premium",
    topBrands: "Santa Teresa, Pomar, Torres, Victoria",
    description: "La vinoteca más completa de Los Teques con más de 15 años de trayectoria. Especializada en vinos venezolanos y una selección curada de rones premium. Cuentan con servicio de delivery y asesoría personalizada para elegir el vino perfecto.",
    rating: 4.7,
    reviewCount: 23,
    verified: true,
    featured: true,
    tags: JSON.stringify(["vinoteca", "delivery", "ron-premium", "vino-nacional", "asesoría"]),
    latitude: 10.3431,
    longitude: -66.8793,
  },
  {
    name: "La Tasca de Juana",
    slug: "la-tasca-de-juana",
    category: "TASCA",
    subcategory: "Taberna",
    zone: "La Hoyada",
    address: "Calle Sucre con Av. Independencia, La Hoyada",
    phone: "0212-3223344",
    whatsapp: "584145678901",
    instagram: "@tascadejuana",
    hours: "Mar-Dom 12:00-23:00",
    happyHour: "Mar-Jue 17:00-19:00",
    priceRange: "$$",
    hasDelivery: false,
    petFriendly: true,
    hasReservations: true,
    specialty: "Vinos por copa, tapas venezolanas, ambiente bohemio",
    topBrands: "Diplomático, Cocuy, Cerveza Regional",
    description: "Una tasca con alma venezolana en el corazón de La Hoyada. Más de 30 etiquetas de vino por copa, tapas artesanales y un ambiente que invita a quedarse. Los jueves tienen noche de vino español con guitarra en vivo. Terraza disponible.",
    rating: 4.9,
    reviewCount: 45,
    verified: true,
    featured: true,
    tags: JSON.stringify(["terraza", "vino-por-copa", "tapas", "música-en-vivo", "noche-española", "pet-friendly"]),
    latitude: 10.3405,
    longitude: -66.8812,
  },
  {
    name: "Bodegón Los Andes",
    slug: "bodegon-los-andes",
    category: "BODEGON",
    subcategory: "Depósito de Licores",
    zone: "San Pedro",
    address: "Av. San Pedro, Frente al Mercado Municipal",
    phone: "0212-3234567",
    whatsapp: "584127890123",
    instagram: "@bodegonlosandes",
    hours: "Lun-Sáb 7:00-19:00",
    priceRange: "$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Licores al mayor, cervezas nacionales, hielo",
    topBrands: "Polar, Regional, Santa Teresa, Cacique",
    description: "El bodegón más económico de Los Teques. Precios de mayoreo al público general con la mayor variedad de cervezas nacionales y rones populares. Ideal para compras en cantidad para reuniones y fiestas. Delivery gratuito en zona de San Pedro.",
    rating: 4.3,
    reviewCount: 18,
    verified: true,
    featured: false,
    tags: JSON.stringify(["mayoreo", "precio-bajo", "cerveza", "fiestas", "delivery-gratis"]),
    latitude: 10.3460,
    longitude: -66.8750,
  },
  {
    name: "Licorería Don Sancho",
    slug: "licoreria-don-sancho",
    category: "LICORERIA",
    subcategory: "Licorería",
    zone: "Centro",
    address: "Los Teques, Estado Miranda",
    phone: "+58 424-2569762",
    whatsapp: "584242569762",
    instagram: "licoreriadonsancho",
    website: "https://licoreria-donsancho.vercel.app/",
    hours: "Lun-Sáb 9:00-20:00",
    priceRange: "$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Licores en promoción, rones, whiskys, cervezas",
    topBrands: "Santa Teresa, Diplomático, Polar, Cacique",
    description: "Licorería Don Sancho, tu tienda de licores de confianza en Los Teques. Variedad en rones, whiskys, cervezas y más. Promociones exclusivas y atención personalizada. ¡Contáctanos por WhatsApp!",
    rating: 4.6,
    reviewCount: 12,
    verified: true,
    featured: true,
    image: "/businesses/donsancho/logo.jpg",
    gallery: JSON.stringify([
      "/businesses/donsancho/lico_1.jpg",
      "/businesses/donsancho/lico_2.jpg",
      "/businesses/donsancho/lico_3.jpg",
      "/businesses/donsancho/lico_4.jpg",
      "/businesses/donsancho/lico_5.jpg",
      "/businesses/donsancho/lico_6.webp",
    ]),
    tags: JSON.stringify(["delivery", "promociones", "whatsapp", "licores-variedad", "los-teques"]),
    latitude: 10.34735266696021,
    longitude: -67.04552552429993,
  },
  {
    name: "Tasca La Cueva",
    slug: "tasca-la-cueva",
    category: "TASCA",
    subcategory: "Bar de Vinos",
    zone: "El Trapiche",
    address: "Av. El Trapiche, Local 7",
    phone: "0212-3256789",
    whatsapp: "584143456789",
    instagram: "@tascalacuevateques",
    hours: "Mié-Dom 18:00-01:00",
    happyHour: "Mié-Vie 18:00-20:00 2x1 en copas",
    priceRange: "$$",
    hasDelivery: false,
    petFriendly: false,
    hasReservations: true,
    specialty: "Cerveza artesanal, vinos orgánicos, tabla de quesos",
    topBrands: "Cerveza Zulia, Tropico, Regional Artesanal",
    description: "Escondida en El Trapiche, La Cueva es el punto de encuentro de los amantes de la cerveza artesanal en Los Teques. Con 12 grifos de cerveza artesanal rotativa, carta de vinos orgánicos y las mejores tablas de quesos y embutidos de la región.",
    rating: 4.6,
    reviewCount: 27,
    verified: true,
    featured: true,
    tags: JSON.stringify(["cerveza-artesanal", "grifos", "vino-orgánico", "tabla-de-quesos", "2x1"]),
    latitude: 10.3380,
    longitude: -66.8845,
  },
  {
    name: "Licorería Premium Los Teques",
    slug: "licoreria-premium-los-teques",
    category: "LICORERIA",
    subcategory: "Licorería Gourmet",
    zone: "Centro",
    address: "C.C. Los Teques Mall, Nivel Plaza",
    phone: "0212-3267890",
    whatsapp: "584156789012",
    instagram: "@premimumlt",
    hours: "Lun-Dom 10:00-22:00",
    priceRange: "$$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Licores importados, champagne, whisky escocés",
    topBrands: "Johnnie Walker, Jack Daniel's, Moët, Chivas Regal",
    description: "La licorería premium del centro comercial Los Teques. Especializada en licores importados de alta gama: whisky escocés, champagne francés, vodka premium y ginebras artesanales. Ideal para regalos corporativos y ocasiones especiales.",
    rating: 4.5,
    reviewCount: 15,
    verified: true,
    featured: false,
    tags: JSON.stringify(["importado", "whisky", "champagne", "regalos", "corporativo"]),
    latitude: 10.3425,
    longitude: -66.8780,
  },
  {
    name: "Bodegón El Paraíso",
    slug: "bodegon-el-paraiso",
    category: "BODEGON",
    subcategory: "Distribuidor",
    zone: "La Hoyada",
    address: "Av. La Hoyada, Frente a la Plaza Bolívar",
    phone: "0212-3278901",
    whatsapp: "584167890123",
    instagram: "@bodegonparaisolt",
    hours: "Lun-Sáb 8:00-18:00",
    priceRange: "$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Distribución de licores, precios de fábrica",
    topBrands: "Todas las marcas nacionales",
    description: "Bodegón y distribuidor con los mejores precios de Los Teques. Trabajan directamente con las distribuidoras nacionales ofreciendo precios de fábrica al público. Servicio de delivery para compras mayores a 5 cajas.",
    rating: 4.1,
    reviewCount: 12,
    verified: false,
    featured: false,
    tags: JSON.stringify(["distribuidor", "precio-fábrica", "mayoreo", "empresarial"]),
    latitude: 10.3410,
    longitude: -66.8820,
  },
  {
    name: "Taberna El Mirador",
    slug: "taberna-el-mirador",
    category: "TASCA",
    subcategory: "Taberna",
    zone: "Centro",
    address: "Calle Páez, Edificio Mirador, PB",
    phone: "0212-3289012",
    whatsapp: "584178901234",
    instagram: "@tabernamirador",
    hours: "Lun-Sáb 17:00-00:00, Dom 12:00-22:00",
    happyHour: "Lun-Vie 17:00-19:00 cerveza nacional 50%",
    priceRange: "$$",
    hasDelivery: false,
    petFriendly: true,
    hasReservations: true,
    specialty: "Ambiente de montaña, ron con limón, tragos clásicos",
    topBrands: "Cacique, Diplomático, Polar",
    description: "Con la mejor vista de Los Teques desde su terraza, El Mirador ofrece un ambiente de taberna de montaña con tragos clásicos bien preparados, ron con limón como tradición local y la mejor carta de cervezas nacionales. Los viernes tienen DJ en vivo.",
    rating: 4.4,
    reviewCount: 19,
    verified: true,
    featured: false,
    tags: JSON.stringify(["terraza", "vista-panorámica", "DJ", "tragos-clásicos", "pet-friendly"]),
    latitude: 10.3445,
    longitude: -66.8798,
  },
  {
    name: "Vinoteca La Terraza",
    slug: "vinoteca-la-terraza",
    category: "LICORERIA",
    subcategory: "Vinoteca",
    zone: "San Pedro",
    address: "Av. San Pedro con Calle 5",
    phone: "0212-3290123",
    whatsapp: "584189012345",
    instagram: "@vinotecalaterraza",
    hours: "Mar-Sáb 11:00-21:00",
    priceRange: "$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Vinos latinoamericanos, espumosos, catas mensuales",
    topBrands: "Zuccardi, Trapiche, Luis Felipe Edwards, Freixenet",
    description: "Vinoteca boutique especializada en vinos latinoamericanos con una propuesta única: catas mensuales temáticas abiertas al público. Cada tercer sábado del mes realizan una cata guiada con maridaje. Delivery disponible para toda el área metropolitana.",
    rating: 4.7,
    reviewCount: 22,
    verified: true,
    featured: true,
    tags: JSON.stringify(["catas-mensuales", "vino-latinoamericano", "espumoso", "maridaje", "boutique"]),
    latitude: 10.3465,
    longitude: -66.8755,
  },
  {
    name: "El Bodegón de Tío Simón",
    slug: "el-bodegon-de-tio-simon",
    category: "BODEGON",
    subcategory: "Bodegón Tradicional",
    zone: "El Trapiche",
    address: "Calle El Trapiche, Local 1",
    phone: "0212-3201234",
    whatsapp: "584190123456",
    instagram: "@bodegontiosimon",
    hours: "Lun-Sáb 7:00-20:00, Dom 8:00-13:00",
    priceRange: "$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Licores para toda ocasión, hielo, piña",
    topBrands: "Polar, Cacique, Santa Teresa, Pomar",
    description: "El bodegón del barrio. Tío Simón lleva 25 años atendiendo a la comunidad de El Trapiche con precios justos y trato familiar. Es el lugar donde encuentras de todo: desde cerveza por cajón hasta rones añejos para regalo. Famoso por su servicio rápido y amable.",
    rating: 4.6,
    reviewCount: 34,
    verified: true,
    featured: false,
    tags: JSON.stringify(["tradicional", "barrio", "24-años", "servicio-rápido", "familiar"]),
    latitude: 10.3385,
    longitude: -66.8840,
  },
  {
    name: "Barra 10",
    slug: "barra-10",
    category: "TASCA",
    subcategory: "Coctelería",
    zone: "Centro",
    address: "Av. Bolívar, Centro Comercial Plaza 10, Local 2",
    phone: "0212-3212345",
    whatsapp: "584101234567",
    instagram: "@barra10teques",
    hours: "Mié-Dom 19:00-02:00",
    happyHour: "Mié 19:00-21:00 cocteles 2x1",
    priceRange: "$$$",
    hasDelivery: false,
    petFriendly: false,
    hasReservations: true,
    specialty: "Coctelería autor, whisky sour, mojitos",
    topBrands: "Hendrick's, Tanqueray, Ron Diplomático, Cointreau",
    description: "La coctelería más sofisticada de Los Teques. Barra 10 ofrece una carta de más de 40 cocteles autor preparados con ingredientes frescos y técnicas de bartending profesional. Ambiente exclusivo con música jazz los jueves y DJ sessions los sábados.",
    rating: 4.8,
    reviewCount: 28,
    verified: true,
    featured: true,
    tags: JSON.stringify(["coctelería", "autor", "jazz", "exclusivo", "bartending", "whisky-sour"]),
    latitude: 10.3435,
    longitude: -66.8785,
  },
  {
    name: "Licorería Cumbres",
    slug: "licoreria-cumbres",
    category: "LICORERIA",
    subcategory: "Licorería General",
    zone: "Cumbres de Curumo",
    address: "Av. Cumbres de Curumo, Local A",
    phone: "0212-3223456",
    whatsapp: "584112345678",
    instagram: "@licoreriacumbres",
    hours: "Lun-Sáb 9:00-21:00, Dom 10:00-15:00",
    priceRange: "$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Variedad completa, oferta para el hogar",
    topBrands: "Todas las marcas nacionales e importadas",
    description: "La licorería de referencia en la zona de Cumbres de Curumo. Amplio surtido que cubre todas las necesidades: desde cerveza para la nevera hasta vinos para una cena especial. Parking disponible y atención personalizada.",
    rating: 4.4,
    reviewCount: 16,
    verified: true,
    featured: false,
    tags: JSON.stringify(["parking", "variedad", "hogar", "cumbres"]),
    latitude: 10.3500,
    longitude: -66.8720,
  },
  {
    name: "Tasca El Rincón Criollo",
    slug: "tasca-el-rincon-criollo",
    category: "TASCA",
    subcategory: "Bar Criollo",
    zone: "La Hoyada",
    address: "Calle Junín, La Hoyada",
    phone: "0212-3234567",
    whatsapp: "584123456789",
    instagram: "@rinconcriollolt",
    hours: "Mar-Dom 12:00-23:00",
    happyHour: "Vie 18:00-20:00",
    priceRange: "$",
    hasDelivery: false,
    petFriendly: true,
    hasReservations: false,
    specialty: "Cerveza fría, tragos criollos, perros calientes",
    topBrands: "Polar, Regional, Cacique",
    description: "El bar criollo por excelencia de La Hoyada. Aquí no hay coctelería de autor: lo que hay es cerveza bien fría, ron con limón, tragos criollos al mejor estilo venezolano y unos perros calientes que son leyenda en Los Teques. Ambiente familiar y casual.",
    rating: 4.5,
    reviewCount: 41,
    verified: true,
    featured: false,
    tags: JSON.stringify(["criollo", "casual", "cerveza-fría", "perros-calientes", "familiar", "pet-friendly"]),
    latitude: 10.3400,
    longitude: -66.8825,
  },
  {
    name: "Bodegón Distribuidora Miranda",
    slug: "bodegon-distribuidora-miranda",
    category: "BODEGON",
    subcategory: "Distribuidor Mayorista",
    zone: "Industrial",
    address: "Zona Industrial Los Teques, Galpón 4",
    phone: "0212-3245678",
    whatsapp: "584134567890",
    hours: "Lun-Vie 8:00-17:00",
    priceRange: "$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Ventas al mayor, eventos, empresas",
    topBrands: "Todas las marcas a precios de distribuidor",
    description: "La opción mayorista de Los Teques. Atienden principalmente a negocios, restaurantes y organizadores de eventos. Precios especiales para compras al por mayor con facturación profesional. Entregan en todo el Estado Miranda.",
    rating: 4.2,
    reviewCount: 9,
    verified: false,
    featured: false,
    tags: JSON.stringify(["mayorista", "empresas", "eventos", "facturación", "Estado Miranda"]),
    latitude: 10.3520,
    longitude: -66.8700,
  },
  {
    name: "La Vinoteca de Don Pedro",
    slug: "la-vinoteca-de-don-pedro",
    category: "LICORERIA",
    subcategory: "Vinoteca Especializada",
    zone: "Centro",
    address: "Pasaje Comercial Centro, Local 12",
    phone: "0212-3256789",
    whatsapp: "584145678901",
    instagram: "@donpedrovinos",
    hours: "Lun-Sáb 10:00-20:00",
    priceRange: "$$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Vinos de guarda, colecciones privadas, maridaje",
    topBrands: "Château Margaux, Barolo, Vega Sicilia, Almaviva",
    description: "Don Pedro es un apasionado del vino que lleva 20 años curando la mejor selección de vinos de guarda de Venezuela. Su vinoteca es un espacio de descubrimiento donde cada botella tiene una historia. Ofrecen servicio de asesoría para maridaje y eventos especiales.",
    rating: 4.9,
    reviewCount: 20,
    verified: true,
    featured: true,
    tags: JSON.stringify(["vino-de-guarda", "colección", "asesoría", "eventos", "premium"]),
    latitude: 10.3438,
    longitude: -66.8795,
  },
  {
    name: "Tasca 4 Esquinas",
    slug: "tasca-4-esquinas",
    category: "TASCA",
    subcategory: "Bar de Esquina",
    zone: "San Pedro",
    address: "Calle 4 con Av. San Pedro",
    phone: "0212-3267890",
    whatsapp: "584156789012",
    instagram: "@tasca4esquinas",
    hours: "Mar-Dom 16:00-00:00",
    priceRange: "$",
    hasDelivery: false,
    petFriendly: true,
    hasReservations: false,
    specialty: "Cerveza, tragos sencillos, billar, dominó",
    topBrands: "Polar, Regional, Cacique",
    description: "La tasca de barrio por antonomasia de San Pedro. Cuatro esquinas donde se cruzan los amigos, las cervezas bien frías y las partidas de dominó que se extienden hasta la madrugada. Ambiente relajado, precios accesibles y la mejor vibra local de Los Teques.",
    rating: 4.3,
    reviewCount: 36,
    verified: true,
    featured: false,
    tags: JSON.stringify(["barrio", "dominó", "billar", "accesible", "relajado", "pet-friendly"]),
    latitude: 10.3470,
    longitude: -66.8745,
  },
  {
    name: "Licorería Express",
    slug: "licoreria-express",
    category: "LICORERIA",
    subcategory: "Conveniencia",
    zone: "Centro",
    address: "Av. Bolívar, Local Express",
    phone: "0212-3278901",
    whatsapp: "584167890123",
    hours: "Lun-Dom 10:00-23:00",
    priceRange: "$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Atención rápida, abierto hasta tarde",
    topBrands: "Polar, Cacique, Santa Teresa, Pomar",
    description: "La opción rápida y confiable del centro de Los Teques. Ubicada en punto estratégico con fácil acceso y parking. Abierta hasta tarde todos los días. Ideal para esa compra de última hora antes de una reunión o celebración. Delivery express en 30 minutos.",
    rating: 4.2,
    reviewCount: 14,
    verified: true,
    featured: false,
    tags: JSON.stringify(["express", "tarde", "parking", "rápido", "30-min"]),
    latitude: 10.3420,
    longitude: -66.8805,
  },
  {
    name: "El Bodegón del Pueblo",
    slug: "el-bodegon-del-pueblo",
    category: "BODEGON",
    subcategory: "Bodegón Comunitario",
    zone: "El Trapiche",
    address: "Calle Principal de El Trapiche",
    phone: "0212-3289012",
    whatsapp: "584178901234",
    instagram: "@bodegondelpueblo",
    hours: "Lun-Sáb 7:00-20:00",
    priceRange: "$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Precios accesibles, atención de barrio",
    topBrands: "Polar, Cacique, Regional",
    description: "El bodegón que conoce a todos sus clientes por su nombre. En El Trapiche desde hace 18 años, este bodegón comunitario se distingue por su atención personalizada y precios que respetan el bolsillo de la familia tequense. Tienen un sistema de puntos por compra frecuente.",
    rating: 4.5,
    reviewCount: 29,
    verified: true,
    featured: false,
    tags: JSON.stringify(["comunitario", "puntos", "familiar", "accesible", "18-años"]),
    latitude: 10.3390,
    longitude: -66.8835,
  },
  {
    name: "Casa del Whisky",
    slug: "casa-del-whisky",
    category: "LICORERIA",
    subcategory: "Whisky Especializado",
    zone: "Centro",
    address: "C.C. Los Teques, Nivel 2, Local 5",
    phone: "0212-3290123",
    whatsapp: "584189012345",
    instagram: "@casadelwhisky_lt",
    hours: "Lun-Sáb 11:00-22:00, Dom 12:00-18:00",
    priceRange: "$$$",
    hasDelivery: true,
    petFriendly: false,
    hasReservations: false,
    specialty: "Whisky escocés, japonés, americano, irlandés",
    topBrands: "Macallan, Lagavulin, Yamazaki, Woodford Reserve, Jameson",
    description: "El paraíso del whisky en Los Teques. Más de 120 etiquetas de las cinco regiones productoras del mundo: Escocia, Irlanda, EE.UU., Japón y Canadá. Realizan catas mensuales de whisky con expertos y ofrecen la mayor selección de single malt de Venezuela.",
    rating: 4.8,
    reviewCount: 17,
    verified: true,
    featured: true,
    tags: JSON.stringify(["whisky", "single-malt", "catas", "mundo", "colección", "especializado"]),
    latitude: 10.3428,
    longitude: -66.8775,
  },
  {
    name: "Tasca La Parroquia",
    slug: "tasca-la-parroquia",
    category: "TASCA",
    subcategory: "Bar Tradicional",
    zone: "Centro",
    address: "Calle La Parroquia, al lado de la Iglesia",
    phone: "0212-3201234",
    whatsapp: "584190123456",
    instagram: "@tascalaparroquia",
    hours: "Lun-Sáb 16:00-23:00, Dom 11:00-18:00",
    happyHour: "Lun-Jue 17:00-19:00",
    priceRange: "$",
    hasDelivery: false,
    petFriendly: false,
    hasReservations: false,
    specialty: "Ron con limón, cerveza, pasapalos criollos",
    topBrands: "Cacique, Polar, Santa Teresa",
    description: "Institución tequense desde 1998. La Parroquia es el lugar donde tres generaciones de tequenses se han encontrado para compartir un ron con limón y los mejores pasapalos criollos. Su terraza con vista a la iglesia es el escenario perfecto para las tardes de Los Teques.",
    rating: 4.7,
    reviewCount: 52,
    verified: true,
    featured: true,
    tags: JSON.stringify(["tradicional", "1998", "terraza", "pasapalos", "generaciones", "rón-con-limón"]),
    latitude: 10.3442,
    longitude: -66.8790,
  },
]

const promotions = [
  { title: "2x1 en copas de vino", description: "Todos los martes y jueves", discount: "2x1", businessSlug: "la-tasca-de-juana" },
  { title: "10% en primera compra", description: "Nuevo cliente en delivery", discount: "10%", businessSlug: "licoreria-el-castillo" },
  { title: "Happy Hour 2x1", description: "Cocteles de autor miércolos", discount: "2x1", businessSlug: "barra-10" },
  { title: "Cerveza 50% off", description: "Cerveza nacional en happy hour", discount: "50%", businessSlug: "taberna-el-mirador" },
  { title: "Cata gratuita de vino", description: "Primer sábado de cada mes", discount: "Gratis", businessSlug: "vinoteca-la-terraza" },
  { title: "Delivery gratis", description: "En compras mayores a Bs. 500", discount: "Envío gratis", businessSlug: "bodegon-los-andes" },
  { title: "Licores en promoción", description: "6 licores seleccionados con precios especiales", discount: "Promo", businessSlug: "licoreria-don-sancho" },
  { title: "Noche de Jazz", description: "Jueves con consumición mínima", discount: "2x1 tragos", businessSlug: "barra-10" },
]

const reviews = [
  { businessSlug: "la-tasca-de-juana", author: "María G.", rating: 5, comment: "El mejor ambiente de Los Teques. Los vinos por copa son una maravilla y las tapas están deliciosas. La terraza es hermosa para una tarde entre amigos." },
  { businessSlug: "la-tasca-de-juana", author: "Carlos R.", rating: 5, comment: "Increíble descubrimiento. La noche española del jueves con guitarra en vivo es única. Volveremos seguro." },
  { businessSlug: "barra-10", author: "Ana L.", rating: 5, comment: "Los mejores cocteles que he probado en Venezuela. El whisky sour es espectacular y el ambiente es de primera." },
  { businessSlug: "licoreria-don-sancho", author: "Pedro M.", rating: 5, comment: "Excelente variedad de licores y los precios en promoción son reales. El WhatsApp responde rápido y el delivery llegó en menos de 30 minutos." },
  { businessSlug: "licoreria-el-castillo", author: "Laura P.", rating: 4, comment: "Muy buena selección de vinos venezolanos. El delivery es rápido y el empaque es cuidado." },
  { businessSlug: "tasca-la-parroquia", author: "José V.", rating: 5, comment: "Un clásico de Los Teques. Mi abuelo venía aquí y yo sigo viniendo. El ron con limón y los pasapalos son de leyenda." },
  { businessSlug: "bodegon-los-andes", author: "Roberto S.", rating: 4, comment: "Los mejores precios de Los Teques sin duda. Ideal para comprar para fiestas y reuniones." },
  { businessSlug: "vinoteca-la-terraza", author: "Isabel C.", rating: 5, comment: "Las catas mensuales son una experiencia increíble. Aprendes mucho y pruebas vinos que no encontrarías en otro lado." },
  { businessSlug: "tasca-4-esquinas", author: "Miguel A.", rating: 4, comment: "El lugar perfecto para una cerveza con amigos sin pretensiones. El ambiente de barrio es lo mejor." },
  { businessSlug: "casa-del-whisky", author: "Fernando T.", rating: 5, comment: "La mayor selección de single malt que he visto en Venezuela. El personal realmente conoce de whisky." },
  { businessSlug: "la-tasca-de-juana", author: "Daniela F.", rating: 4, comment: "Pet friendly y con terraza, no se puede pedir más. Los precios son justos para la calidad." },
  { businessSlug: "tasca-el-rincon-criollo", author: "Luis H.", rating: 5, comment: "Los perros calientes son los mejores de Los Teques. Cerveza fría y buen ambiente, simple y perfecto." },
]

async function main() {
  console.log("Seeding database...")

  // Create businesses
  for (const b of businesses) {
    await db.business.create({ data: b })
    console.log(`  Created: ${b.name}`)
  }

  // Create promotions
  for (const p of promotions) {
    const business = await db.business.findUnique({ where: { slug: p.businessSlug } })
    if (business) {
      await db.promotion.create({
        data: {
          title: p.title,
          description: p.description,
          discount: p.discount,
          businessId: business.id,
          startsAt: new Date(),
          endsAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        },
      })
      console.log(`  Promotion: ${p.title}`)
    }
  }

  // Create reviews
  for (const r of reviews) {
    const business = await db.business.findUnique({ where: { slug: r.businessSlug } })
    if (business) {
      await db.review.create({
        data: {
          businessId: business.id,
          author: r.author,
          rating: r.rating,
          comment: r.comment,
        },
      })
      console.log(`  Review: ${r.author} → ${business.name}`)
    }
  }

  // Update aggregate rating
  const allBusinesses = await db.business.findMany({ include: { reviews: true } })
  for (const b of allBusinesses) {
    if (b.reviews.length > 0) {
      const avgRating = b.reviews.reduce((sum, r) => sum + r.rating, 0) / b.reviews.length
      await db.business.update({
        where: { id: b.id },
        data: { rating: Math.round(avgRating * 10) / 10, reviewCount: b.reviews.length },
      })
    }
  }

  console.log(`\nDone! ${businesses.length} businesses, ${promotions.length} promotions, ${reviews.length} reviews`)
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect())